export * from "./Agenda";
export * from "./Alumno";
export * from "./Clase";
export * from "./Feriado";
export * from "./Grupo";
export * from "./Modelo";
export * from "./Molde";
export * from "./MovimientoPendiente";
export * from "./Vacante";
